## Documentation: http://docs.travis-ci.com/user/languages/python/
language: python
os:
  - linux
python:
  - 3.5

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran

install:
  - pip install flake8
  - pip install .

script:
  - flake8
  - pytest
